title: Martin sertin
SEOTitle: Martin Blog
header-img: img/home-bg-art.jpg
email: alialibakhshi9898@gmail.com
description: "Machine learning"
keyword: "python, FastAPI,"
url: "https://aliowx.github.io"
baseurl: ""

future: true

highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-feed

gems:
  - jekyll-feed


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sidebar: true
sidebar-about-description: ""
sidebar-avatar: img/1.png

chrome-tab-theme-color: "#000000"
service-worker: true

page-mathjax: false
